---
title: "Sentiment Analysis of Political Leaders' Tweets and the SPY"
author: Moko Sharma
output: pdf_document 
---

# Introduction

## Loading in the Data for Trump and Pence

```{r warning=FALSE}
library( ggplot2 )
library(lubridate)  

generateFileName <- function( fileName ) {
  dataFolder  <- '../../data/'
  paste( dataFolder, fileName, sep = '')
}

trumpDf     <- read.csv( generateFileName( 'realDonaldTrump.csv' ))
mikePenceDf <- read.csv( generateFileName( 'VP.csv' ))
```

## Trump's Dataframe

```{r}
head( trumpDf )
summary( trumpDf )
names(trumpDf)[names(trumpDf) == "realDonaldTrump.Vader.Sentiment.Score" ] <- 'sentimentscore'
```

## Histogram of the Range of the SPY for the Days Trump Tweeted 

```{r}
hist( x    = trumpDf$range,
      main = "Histogram of the SPY Price Range", 
      xlab = "SPY Price Range",
      col  = 'blue' )
```

It is clear from the Histogram that the distribution of the SPY price range is __Right Skewed__ so, we will be using the __Log Transform__ to transform the data.

```{r}
logTrumpPriceRange <- log( trumpDf$range )

hist( x    = logTrumpPriceRange,
      main = "Histogram of the SPY Price Range", 
      xlab = "SPY Price Range",
      col  = 'blue' )
```

## Plots

```{r warning=FALSE}
ggplot( trumpDf, aes( as.Date( date ))) +
  geom_line( aes( y = logTrumpPriceRange ), color = 'red' ) + 
  scale_x_date( 'Date' ) + 
  ylab( 'Log SPY Price Range' ) +
  ggtitle( 'Log SPY Price Range vs. Dates Trump Tweeted' )
```

```{r}
plot( x = logTrumpPriceRange,
      y = trumpDf$sentimentscore )
```



```{r}
trumpCor.test <-
  cor.test( x = trumpDf$range, 
            y = trumpDf$realDonaldTrump.Vader.Sentiment.Score )
trumpCor.test
```



## Mike Pence's Dataframe

```{r}
head( mikePenceDf )
summary( mikePenceDf )
```